# Generated by Django 3.2.9 on 2021-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApplication', '0002_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
